from datetime import date
from typing import Protocol

import pandas as pd


class MarketDataProvider(Protocol):
    def get_trade_calendar(self, start: date, end: date) -> pd.DataFrame: ...

    def get_stock_basic(self) -> pd.DataFrame: ...

    def get_daily(self, trade_date: date) -> pd.DataFrame: ...

    def get_adj_factor(self, trade_date: date) -> pd.DataFrame: ...

    def get_daily_basic(self, trade_date: date) -> pd.DataFrame: ...

    def get_index_daily(self, trade_date: date, codes: list[str]) -> pd.DataFrame: ...

    def get_index_daily_range(self, ts_code: str, start: date, end: date) -> pd.DataFrame: ...

    def get_stock_st(self, trade_date: date) -> pd.DataFrame: ...

    def get_suspend_daily(self, trade_date: date) -> pd.DataFrame: ...

    def get_stock_limit(self, trade_date: date) -> pd.DataFrame: ...

    def get_sector_classification(self) -> pd.DataFrame: ...

    def get_sector_members(self) -> pd.DataFrame: ...


class OptionalMarketDataProvider(Protocol):
    def get_sector_moneyflow(self, trade_date: date) -> pd.DataFrame: ...

    def get_stock_moneyflow(self, trade_date: date) -> pd.DataFrame: ...

    def get_limit_pool(self, trade_date: date) -> pd.DataFrame: ...

    def get_hot_concepts(self, trade_date: date) -> pd.DataFrame: ...
